/**
 * Fake @wailsio/runtime for the pure-frontend mock preview (dev only).
 *
 * vite.config.ts swaps this module in for "@wailsio/runtime" ONLY when Vite
 * runs with `--mode mock` (npm run dev:mock). In every other mode the real
 * runtime package is used and this file is never part of the build graph.
 *
 * Surface coverage (grep-verified against every "@wailsio/runtime" import in
 * src/ and frontend/bindings/):
 *   - bindings/.../core/app.ts       → Call.ByID, CancellablePromise (type), Create
 *   - bindings/.../core/models.ts    → Create
 *   - src/App.vue                    → Application (Quit), Window (Minimise /
 *                                      ToggleMaximise / IsMaximised / Hide)
 *   - src/lib/linkHandler.ts, src/views/Docs.vue → Browser.OpenURL
 *   - src/lib/safeArea.ts            → Events.On (never fires; no native
 *                                      insets in the mock)
 *
 * Call.ByID dispatches through the numeric method-ID table (extracted from the
 * generated app.ts) to the handler table in mockData.ts. Unknown IDs and
 * unknown method names are logged AND rejected — a missing mock must be
 * visible, never silently swallowed.
 */

import { handlers, mockServerPort, mockServerRunning, mockLoadedModels, mockAddServerLog, mockChatReply, mockChatThinkParts } from './mockData'

// ─── CancellablePromise ──────────────────────────────────────────────────────

/**
 * Stand-in for the runtime's CancellablePromise. The generated bindings only
 * use it as a return TYPE, so at runtime a plain promise subclass with a no-op
 * cancel() is enough.
 */
export class CancellablePromise<T = unknown> extends Promise<T> {
  oncancelled: (() => void) | null = null
  cancel(): void {
    // Nothing in flight to cancel in the mock; no-op.
  }
}

// ─── Call dispatch ───────────────────────────────────────────────────────────

// Numeric method-ID → bare method name. Extracted from
// bindings/github.com/CodeNeow/MyLlama/core/app.ts ($Call.ByID(…)
// calls, generated by `wails3 generate bindings`). If bindings are ever
// regenerated with new methods, extend this table (unknown IDs reject loudly).
const methodIds: Record<number, string> = {
  3564127659: 'BenchmarkModel',
  4034392886: 'BrowseLlamaCppDir',
  2839732354: 'BrowseLlamaCppDownloadDir',
  4058621793: 'BrowseModelDownloadDir',
  1383123962: 'BrowseModelsDir',
  2600950860: 'CancelDownloadTask',
  8953589: 'CheckForUpdate',
  4273232820: 'GetAppVersion',
  1302194621: 'GetCPU',
  2835900922: 'GetCUDA',
  3248505227: 'GetConfig',
  1746999888: 'GetDisk',
  2380172504: 'GetDownloadSource',
  650852813: 'GetDownloadTasks',
  36030513: 'GetGPU',
  1087173235: 'GetLlamaCpp',
  1325253841: 'GetLlamaCppDownloadStatus',
  467291630: 'GetLoadedModels',
  1825090130: 'GetMemory',
  1343528888: 'GetModelConfig',
  3856182128: 'GetModelDescription',
  3827624353: 'GetModelFiles',
  1239728199: 'GetModelMaxFileSize',
  68250215: 'GetModels',
  1410600887: 'GetMonitorStatus',
  1742051203: 'GetOS',
  3167960667: 'GetRemoteDoc',
  2134401773: 'GetSafeArea',
  923718408: 'GetServerConfig',
  795529405: 'GetServerLogsSince',
  1189515840: 'GetServerStatus',
  3756917252: 'GetSystemInfo',
  3051828874: 'GetUpdateDownloadStatus',
  1932284239: 'InstallUpdate',
  612386522: 'PauseDownloadTask',
  987681577: 'PauseLlamaCppDownload',
  1283513860: 'RefreshModels',
  1998385817: 'ResumeDownloadTask',
  2867782122: 'ResumeLlamaCppDownload',
  2795962746: 'RetryDownloadTask',
  4225909797: 'SaveModelConfig',
  1564074031: 'SaveServerConfig',
  3530747576: 'SearchDownloads',
  2691071663: 'SetApiRouteMode',
  2014041732: 'SetDownloadSource',
  3446872155: 'SetLanguage',
  987292370: 'SetLlamaCppDownloadDir',
  4262946321: 'SetModelDownloadDir',
  2767063690: 'SetModelsDir',
  3725857053: 'SetOnboardingDismissed',
  528273016: 'SetSidebarCollapsed',
  2940332114: 'SetTheme',
  1566242230: 'SetTrayEnabled',
  2008696521: 'StartDownload',
  1108336451: 'StartLlamaCppDownload',
  96158786: 'StartServer',
  3289498203: 'StartServerWithModel',
  2747421932: 'StartUpdateDownload',
  4167888033: 'StopLlamaCppDownload',
  1483274300: 'StopServer',
  38776446: 'StopUpdateDownload',
  899609304: 'TuneModelConfig',
  125436185: 'UnloadModel',
}

function callByName(name: string, args: any[]): Promise<any> {
  const handler = handlers[name]
  if (!handler) {
    console.warn('[mockRuntime] no mock handler for binding method "' + name + '"')
    return Promise.reject(new Error('[mockRuntime] unmocked binding method: ' + name))
  }
  return Promise.resolve()
    .then(() => handler(...args))
    .catch((err: unknown) => {
      // Surface handler failures in the console too (e.g. validation rejects).
      console.warn('[mockRuntime] binding "' + name + '" rejected:', err)
      throw err
    })
}

function unmocked(kind: string, key: unknown): Promise<never> {
  console.warn('[mockRuntime] unknown ' + kind, key)
  return Promise.reject(new Error('[mockRuntime] unknown ' + kind + ': ' + String(key)))
}

/**
 * Mirror of the runtime's `Call` namespace shape
 * ({ Call, ByID, ByName, RuntimeError }): the generated bindings use
 * `$Call.ByID(<id>, ...args)`, ByName/Call are kept for completeness.
 */
export const Call = {
  ByID(methodID: number, ...args: any[]): Promise<any> {
    const name = methodIds[methodID]
    if (!name) return unmocked('binding method id', methodID)
    return callByName(name, args)
  },
  ByName(methodName: string, ...args: any[]): Promise<any> {
    return callByName(methodName, args)
  },
  Call(options: { methodName?: string; methodID?: number; args?: any[] }): Promise<any> {
    if (typeof options?.methodName === 'string') return callByName(options.methodName, options.args ?? [])
    if (typeof options?.methodID === 'number') return Call.ByID(options.methodID, ...(options.args ?? []))
    return unmocked('Call options', options)
  },
  RuntimeError: class MockRuntimeError extends Error {},
}

// ─── Create (type-coercion helpers used by the generated bindings) ──────────

// The mock handlers already return plain JSON-shaped data, so every coercion
// is a pass-through (arrays still map their elements through the given
// creator, matching the real semantics for nested binding classes).
const passthrough = (source: any) => source

export const Create = {
  Any: passthrough,
  ByteSlice: passthrough,
  Array: (element: (s: any) => any) => (source: any) => (Array.isArray(source) ? source.map(element) : source),
  Map: () => passthrough,
  Nullable: (element: (s: any) => any) => (source: any) => (source == null ? source : element(source)),
  Struct: () => passthrough,
  DateFromTime: passthrough,
}

// ─── Application / Window / Browser ──────────────────────────────────────────

export const Application = {
  Hide: () => Promise.resolve(),
  Show: () => Promise.resolve(),
  Quit: () => Promise.resolve(),
}

export const Window = {
  Minimise: () => Promise.resolve(),
  ToggleMaximise: () => Promise.resolve(),
  Maximise: () => Promise.resolve(),
  Unmaximise: () => Promise.resolve(),
  IsMaximised: () => Promise.resolve(false),
  IsMinimised: () => Promise.resolve(false),
  Hide: () => Promise.resolve(),
  Show: () => Promise.resolve(),
  Close: () => Promise.resolve(),
  SetTitle: (_title: string) => Promise.resolve(),
  Center: () => Promise.resolve(),
}

export const Browser = {
  OpenURL: (_url: string | URL) => Promise.resolve(),
}

// Events shim for src/lib/safeArea.ts (the only Events consumer): On returns
// an unsubscribe function and never fires — the mock has no native system-bar
// insets to push, so safe area stays at the env() CSS baseline.
export const Events = {
  On: (_name: string, _callback: (ev: unknown) => void) => () => {},
}

// ─── fetch interception (chat page talks to llama-server directly) ──────────

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))

const json = (body: unknown, status = 200): Response =>
  new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  })

/** OpenAI-compatible SSE stream with a visibly paced typing effect.
 * Honors the request's AbortSignal: the chat page's stop button aborts the
 * fetch, so the stream must stop enqueueing and error the controller (mirrors
 * a real fetch, whose body reader rejects with the abort reason).
 * With the ?sc=chatthink scenario active, a reasoning prelude streams first
 * as `reasoning_content` deltas (design frame ⑥ collapsible think block). */
function chatCompletionResponse(signal?: AbortSignal | null): Response {
  const encoder = new TextEncoder()
  const reply = mockChatReply()
  // 2-character slices ≈ one CJK token per chunk, 30ms apart.
  const pieces: string[] = []
  for (let i = 0; i < reply.length; i += 2) pieces.push(reply.slice(i, i + 2))
  const think = mockChatThinkParts()
  const reasoningPieces: string[] = []
  if (think) {
    for (let i = 0; i < think.reasoning.length; i += 2) reasoningPieces.push(think.reasoning.slice(i, i + 2))
  }
  // chatthink scenario: a visibly slower pace so the transient streaming
  // states (expanded think block / typing dots / red stop) stay observable
  // during the walkthrough capture.
  const pace = think ? 150 : 30
  const body = new ReadableStream<Uint8Array>({
    async start(controller) {
      // Abort mid-stream: surface the abort reason to the body reader so the
      // chat page's catch sees the same AbortError a real server would cause.
      const onAbort = () => {
        try {
          controller.error(signal?.reason ?? new DOMException('The user aborted a request.', 'AbortError'))
        } catch {
          // Stream already closed or errored (abort raced the completion) — nothing to abort.
        }
      }
      if (signal?.aborted) {
        onAbort()
        return
      }
      signal?.addEventListener('abort', onAbort, { once: true })
      try {
        for (const piece of reasoningPieces) {
          await sleep(pace)
          if (signal?.aborted) return // listener already errored the controller
          try {
            controller.enqueue(
              encoder.encode('data: ' + JSON.stringify({ choices: [{ delta: { reasoning_content: piece } }] }) + '\n\n'),
            )
          } catch {
            // Abort raced the enqueue (flag read just before the listener fired):
            // the controller is already errored, so stop feeding it silently.
            return
          }
        }
        for (const piece of pieces) {
          await sleep(pace)
          if (signal?.aborted) return // listener already errored the controller
          try {
            controller.enqueue(
              encoder.encode('data: ' + JSON.stringify({ choices: [{ delta: { content: piece } }] }) + '\n\n'),
            )
          } catch {
            // Abort raced the enqueue (flag read just before the listener fired):
            // the controller is already errored, so stop feeding it silently.
            return
          }
        }
        try {
          controller.enqueue(encoder.encode('data: [DONE]\n\n'))
          controller.close()
        } catch {
          // Same abort race on the closing chunk: the reader already got the
          // abort reason, closing a dead controller is a no-op.
        }
      } finally {
        signal?.removeEventListener('abort', onAbort)
      }
    },
  })
  return new Response(body, { status: 200, headers: { 'Content-Type': 'text/event-stream' } })
}

/** Router/OpenAI model list shared with the GetLoadedModels mock state. */
function modelsResponse(directModeFallback: boolean): Response {
  const data = mockLoadedModels().map((m) =>
    directModeFallback
      ? { id: m.id, object: 'model' }
      : { id: m.id, object: 'model', status: { value: m.status } },
  )
  return json({ object: 'list', data })
}

async function handleMockServerRequest(url: URL, init: RequestInit | undefined): Promise<Response> {
  const path = url.pathname
  const method = (init?.method ?? 'GET').toUpperCase()
  // Direct-mode fallback shape (src/lib/chat.ts): every served model is loaded.
  if (method === 'GET' && path === '/models') {
    return mockServerRunning() ? modelsResponse(false) : json({ error: { message: 'llama-server is not running (mock)' } }, 503)
  }
  if (method === 'GET' && path === '/v1/models') {
    return mockServerRunning() ? modelsResponse(true) : json({ error: { message: 'llama-server is not running (mock)' } }, 503)
  }
  if (method === 'POST' && path === '/v1/chat/completions') {
    if (!mockServerRunning()) {
      return json({ error: { message: 'llama-server is not running (mock)' } }, 503)
    }
    mockAddServerLog('srv  update_slots: all slots are busy')
    return chatCompletionResponse(init?.signal)
  }
  if (method === 'POST' && path === '/models/unload') {
    mockAddServerLog('[INFO] router: model unload request accepted (mock)')
    return json({ ok: true })
  }
  return json({ error: { message: 'mock llama-server has no route for ' + method + ' ' + path } }, 404)
}

// Install once per page: requests aimed at the mock llama-server
// (127.0.0.1:<mockServerPort()>) are answered locally, everything else goes to
// the real network untouched.
const fetchMarker = '__llamaMockFetchInstalled' as const
if (!(globalThis as any)[fetchMarker]) {
  ;(globalThis as any)[fetchMarker] = true
  const originalFetch = globalThis.fetch.bind(globalThis)
  globalThis.fetch = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
    let url: URL | null = null
    try {
      url = new URL(typeof input === 'string' ? input : input instanceof URL ? input.href : input.url)
    } catch {
      url = null
    }
    if (url && url.hostname === '127.0.0.1' && url.port === String(mockServerPort())) {
      return handleMockServerRequest(url, init)
    }
    return originalFetch(input, init)
  }
}
